
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:11.2.0
    environment:
      AWS_SDK_LOAD_CONFIG: true
      GF_AUTH_BASIC_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-grafanapw}
      GF_INSTALL_PLUGINS: redis-app,redis-datasource,grafana-lokiexplore-app
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "${GF_PORT:-3000}:3000"

  loki-gateway:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "${LOKI_PORT:-3100}:3100"
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./config/prometheus:/etc/config
    command:
      - "--config.file=/etc/config/prometheus.yaml"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
      - "--web.enable-remote-write-receiver"
      - "--storage.tsdb.retention.time=10d"
      - "--storage.tsdb.wal-compression"
      - "--storage.tsdb.min-block-duration=2h"
      - "--storage.tsdb.max-block-duration=2h"
volumes:
 grafana_data:
